// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLw9CpoS1ECFm8gtuiJI_Mxc7RkHltRA',
    appId: '1:408849567092:web:adfebc8058a5369fd93021',
    messagingSenderId: '408849567092',
    projectId: 'pushdemo-48503',
    authDomain: 'pushdemo-48503.firebaseapp.com',
    storageBucket: 'pushdemo-48503.firebasestorage.app',
    measurementId: 'G-TYJ50MLQ52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEUq_ZoOq5FO98hwSr9tN3IBB0J7lUcfY',
    appId: '1:408849567092:android:15c539461f6293dcd93021',
    messagingSenderId: '408849567092',
    projectId: 'pushdemo-48503',
    storageBucket: 'pushdemo-48503.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrWnN3Clza9wGe6GPdQl1x4kPPNTLGlPI',
    appId: '1:408849567092:ios:3f6b8c8e1e13c06ed93021',
    messagingSenderId: '408849567092',
    projectId: 'pushdemo-48503',
    storageBucket: 'pushdemo-48503.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrWnN3Clza9wGe6GPdQl1x4kPPNTLGlPI',
    appId: '1:408849567092:ios:3f6b8c8e1e13c06ed93021',
    messagingSenderId: '408849567092',
    projectId: 'pushdemo-48503',
    storageBucket: 'pushdemo-48503.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJLw9CpoS1ECFm8gtuiJI_Mxc7RkHltRA',
    appId: '1:408849567092:web:7396c85bb2b366dfd93021',
    messagingSenderId: '408849567092',
    projectId: 'pushdemo-48503',
    authDomain: 'pushdemo-48503.firebaseapp.com',
    storageBucket: 'pushdemo-48503.firebasestorage.app',
    measurementId: 'G-66KTWW6ZDZ',
  );
}
